apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: "{{ .Release.Name }}-web"
  annotations:
    {{- .Values.web.ingress.annotations | toYaml | nindent 4 }}
spec:
  rules:
    - host: "{{ .Values.web.hostname }}"
      http:
        paths:
          - path: '{{ .Values.web.path | default "/" }}'
            pathType: Prefix
            backend:
              service:
                name: "{{ .Release.Name }}-web"
                port:
                  name: http
  {{- if .Values.web.ingress.tls.enabled }}
  tls:
    - secretName: newsmap-js-cert
      hosts:
        - "{{ .Values.web.hostname }}"
  {{- end }}